[build]
  # The directory for your frontend or built files (optional)
  publish = "dist" # Replace with your build directory (e.g., "build" or "public")
  
  # The directory where your backend/serverless functions are located
  functions = "backend/functions"

[functions]
  # Specify the Node.js version (optional, based on your backend requirements)
  node_bundler = "esbuild"
  included_files = ["backend/**/*"] # Include all backend files for deployment

[[redirects]]
  # Redirect API requests to serverless functions
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200