[build]
  # The directory for your compiled Netlify functions
  functions = "build"

[functions]
  # Include additional files if needed
  included_files = ["src/**/*", ".env"]

[[redirects]]
  # Redirect API requests to your serverless functions
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
