[build]
  # No frontend static files, so leave 'publish' empty or omit it
  publish = "" 

  # Functions directory is the root folder
  functions = "."

[functions]
  # Ensure all root-level files are included
  included_files = ["**/*"] 

[[redirects]]
  # Redirect API requests to serverless functions
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200