const data = {
	products: [
		{
			name: "hoody sweater",
			slug: "nigeria-hoody",
			category: "hoody",
			image: "/images/1.jpg",
			price: 40,
			brand: "de nuelx",
			rating: 5,
			numReview: 8,
			countInStock: 10,
			description: " red hoody sweater",
		},
		{
			name: "hoody sweater",
			slug: "demark-hoody",
			category: "hoody",
			image: "/images/download (2).jpeg",
			price: 40,
			brand: "de nuelx",
			rating: 5,
			numReview: 8,
			countInStock: 10,
			description: " black hoody sweater",
		},
		{
			name: "nike shoes",
			slug: "savahan-f",
			category: "canvas shoes",
			image: "/images/images (15).jpeg",
			price: 40,
			brand: "nike",
			rating: 5,
			numReview: 8,
			countInStock: 10,
			description: " men shoes",
		},
		{
			name: "lavida shoes",
			slug: "lavida-shoes-fashion",
			category: "canvas shoes",
			image: "/images/images (17).jpeg",
			price: 40,
			brand: "lavida",
			rating: 5,
			numReview: 8,
			countInStock: 10,
			description: " men shoes",
		},
		{
			name: "catual shoes",
			slug: "men-catual-shoes",
			category: "canvas shoes",
			image: "/images/images (18).jpeg",
			price: 40,
			brand: "robbins",
			rating: 5,
			numReview: 8,
			countInStock: 10,
			description: " men shoes",
		},
		{
			name: "nike shoes NBA",
			slug: "nike-fashion",
			category: "canvas shoes",
			image: "/images/images (19).jpeg",
			price: 40,
			brand: "nike",
			rating: 5,
			numReview: 8,
			countInStock: 10,
			description: " men shoes",
		},
		{
			name: "apple watch",
			slug: "apple-fashion-watch",
			category: "watch",
			image: "/images/images (20).jpeg",
			price: 40,
			brand: "apple",
			rating: 5,
			numReview: 8,
			countInStock: 10,
			description: " smart watch",
		},
		{
			name: "apple watch",
			slug: "stylish-watch",
			category: "watch",
			image: "/images/images (21).jpeg",
			price: 110,
			brand: "apple",
			rating: 5,
			numReview: 8,
			countInStock: 10,
			description: " smart watch",
		},
		{
			name: "iPhone 14 pro max",
			slug: "iphone",
			category: "mobile",
			image: "/images/images (22).jpeg",
			price: 40,
			brand: "apple",
			rating: 5,
			numReview: 8,
			countInStock: 10,
			description: " iphone",
		},
		{
			name: "iphone 13pro max",
			slug: "iphone13",
			category: "mobile",
			image: "/images/images (25).jpeg",
			price: 40,
			brand: "apple",
			rating: 5,
			numReview: 8,
			countInStock: 10,
			description: " iphone 13pro max",
		},
		{
			name: "nike shoes",
			slug: "nirra-nike",
			category: "canvas shoes",
			image: "/images/images (26).jpeg",
			price: 40,
			brand: "nike",
			rating: 5,
			numReview: 8,
			countInStock: 10,
			description: " men shoes",
		},
		{
			name: "nike shoes",
			slug: "nigeria-nike",
			category: "canvas shoes",
			image: "/images/images (27).jpeg",
			price: 40,
			brand: "nike",
			rating: 5,
			numReview: 8,
			countInStock: 10,
			description: " men shoes",
		},
		{
			name: "nike shoes",
			slug: "nigeriainikky",
			category: "canvas shoes",
			image: "/images/images (28).jpeg",
			price: 40,
			brand: "nike",
			rating: 5,
			numReview: 8,
			countInStock: 10,
			description: " men shoes",
		},
		{
			name: "nike shoes",
			slug: "nigeria",
			category: "canvas shoes",
			image: "/images/images (29).jpeg",
			price: 40,
			brand: "nike",
			rating: 5,
			numReview: 8,
			countInStock: 10,
			description: " men shoes",
		},
		{
			name: "apple mac retina",
			slug: "macbook-retina",
			category: "laptop",
			image: "/images/images (30).jpeg",
			price: 40,
			brand: "apple",
			rating: 5,
			numReview: 8,
			countInStock: 10,
			description: " macintosh",
		},
		{
			name: "macbook air",
			slug: "apple-macbook-air",
			category: "laptop",
			image: "/images/images (31).jpeg",
			price: 40,
			brand: "apple-macbook-air",
			rating: 5,
			numReview: 8,
			countInStock: 10,
			description: " laptop",
		},
		{
			name: "macbook pro",
			slug: "apple-macbook-pro",
			category: "laptop",
			image: "/images/images (32).jpeg",
			price: 40,
			brand: "apple",
			rating: 5,
			numReview: 8,
			countInStock: 10,
			description: " laptop",
		},
		{
			name: "nike shoes",
			slug: "brouncer-nike",
			category: "canvas shoes",
			image: "/images/images (33).jpeg",
			price: 40,
			brand: "nike",
			rating: 5,
			numReview: 8,
			countInStock: 10,
			description: " men shoes",
		},
		{
			name: "casio sleek watch",
			slug: "casio-watch",
			category: "watch",
			image: "/images/images (34).jpeg",
			price: 40,
			brand: "casio",
			rating: 5,
			numReview: 8,
			countInStock: 10,
			description: " men shoes",
		},
		{
			name: "edifice watch",
			slug: "stylish-fashion-men-watch",
			category: "watch",
			image: "/images/images (35).jpeg",
			price: 40,
			brand: "edifice",
			rating: 5,
			numReview: 8,
			countInStock: 10,
			description: " men shoes",
		},
	],


};
export default data;
