const data = {
  products: [
    {
      name: "Red Hoody Sweater",
      slug: "nigeria-hoody",
      category: "Hoody",
      image: "/images/1.jpg",
      price: 40,
      brand: "De Nuelx",
      rating: 5,
      numReview: 8,
      countInStock: 10,
      color: "Red",
      size: ["S", "M", "L", "XL"],
      material: "100% Premium Cotton",
      careInstructions: "Machine wash cold, tumble dry low",
      keyFeatures: [
        "Soft and breathable fabric",
        "Adjustable hood with drawstrings",
        "Front kangaroo pocket for convenience",
        "Ribbed cuffs and hem for a snug fit",
      ],
      description:
        "A vibrant red hoody sweater designed for both comfort and style. This versatile piece is perfect for casual outings, lounging, or layering during colder weather.",
    },

    {
      name: "Black Hoody Sweater",
      slug: "demark-hoody",
      category: "Hoody",
      image: "/images/download (2).jpeg",
      price: 40,
      brand: "De Nuelx",
      rating: 5,
      numReview: 8,
      countInStock: 10,
      color: "Black",
      size: ["S", "M", "L", "XL"],
      material: "80% Cotton, 20% Polyester",
      careInstructions: "Machine wash cold, do not bleach",
      keyFeatures: [
        "Timeless black color",
        "Adjustable hood and cozy fit",
        "Durable stitching for long-lasting use",
        "Front pocket for easy storage",
      ],
      description:
        "Classic black hoody sweater offering warmth and durability. Its versatile design makes it an ideal choice for everyday wear or layering.",
    },

    {
      name: "Nike Canvas Shoes",
      slug: "savahan-f",
      category: "Canvas Shoes",
      image: "/images/images (15).jpeg",
      price: 40,
      brand: "Nike",
      rating: 5,
      numReview: 8,
      countInStock: 10,
      color: "White with Black Accents",
      size: [38, 39, 40, 41, 42, 43, 44],
      material: "Canvas upper, rubber sole",
      keyFeatures: [
        "Lightweight and breathable design",
        "Durable sole with anti-slip grip",
        "Classic Nike branding for a stylish look",
        "Comfortable insole for all-day wear",
      ],
      description:
        "Step out in style with these Nike canvas shoes. Perfect for both casual and sporty looks, they deliver unmatched comfort and timeless design.",
    },

    {
      name: "Lavida Men’s Shoes",
      slug: "lavida-shoes-fashion",
      category: "Canvas Shoes",
      image: "/images/images (17).jpeg",
      price: 40,
      brand: "Lavida",
      rating: 5,
      numReview: 8,
      countInStock: 10,
      color: "Navy Blue",
      size: [38, 39, 40, 41, 42, 43, 44],
      material: "Synthetic upper, rubber sole",
      keyFeatures: [
        "Sleek and stylish design",
        "Cushioned sole for maximum comfort",
        "Durable construction for everyday use",
        "Lace-up closure for a secure fit",
      ],
      description:
        "Lavida men’s shoes are perfect for the modern man. Combining elegance and comfort, these shoes are a wardrobe essential for casual and formal occasions alike.",
    },

    {
      name: "Apple Watch Series 8",
      slug: "apple-fashion-watch",
      category: "Watch",
      image: "/images/images (20).jpeg",
      price: 90,
      brand: "Apple",
      rating: 5,
      numReview: 8,
      countInStock: 10,
      color: "Silver",
      dimensions: "41mm or 45mm case sizes",
      material: "Aluminum case with Ion-X strengthened glass",
      connectivity: ["Wi-Fi", "Bluetooth", "GPS"],
      keyFeatures: [
        "Heart rate monitoring and fitness tracking",
        "Bright, always-on Retina display",
        "Water-resistant up to 50 meters",
        "Seamless integration with iOS devices",
      ],
      description:
        "Stay connected and on top of your health with the Apple Watch Series 8. Designed with cutting-edge technology, this smartwatch combines functionality with sleek style.",
    },

    {
      name: "HP Pavilion 15",
      slug: "hp-pavillion-15",
      category: "Laptop",
      image: "/images/images (29).jpeg",
      price: 140,
      brand: "HP",
      rating: 5,
      numReview: 8,
      countInStock: 10,
      color: "Silver",
      screenSize: "15.6 inches",
      processor: "Intel Core i5",
      RAM: "8GB",
      storage: "256GB SSD",
      keyFeatures: [
        "Full HD display for vivid visuals",
        "Lightweight and portable design",
        "Powerful performance for multitasking",
        "Preloaded with Windows 11",
      ],
      description:
        "The HP Pavilion 15 is a versatile laptop tailored for productivity and entertainment. Enjoy seamless performance and stunning visuals in a sleek design.",
    },
    {
      name: "Apple MacBook Pro",
      slug: "apple-macbook-pro",
      category: "Laptop",
      image: "/images/images (32).jpeg",
      price: 640,
      brand: "Apple",
      rating: 5,
      numReview: 8,
      countInStock: 10,
      color: "Space Gray",
      screenSize: "16 inches",
      processor: "Apple M2 Pro Chip",
      RAM: "16GB",
      storage: "512GB SSD",
      keyFeatures: [
        "Liquid Retina XDR display for brilliant colors",
        "All-day battery life",
        "Magic Keyboard with Touch ID",
        "Supports professional apps for creators",
      ],
      description:
        "Experience top-tier performance with the Apple MacBook Pro. Designed for creators and professionals, it combines advanced power with elegant design.",
    },

    {
      name: "iPhone 15 Pro Max",
      slug: "iphone15",
      category: "Mobile",
      image: "/images/images (26).jpeg",
      price: 440,
      brand: "Apple",
      rating: 5,
      numReview: 8,
      countInStock: 10,
      color: "Deep Blue Titanium",
      screenSize: "6.7 inches",
      storage: ["128GB", "256GB", "512GB", "1TB"],
      camera: "48MP Main Camera, 12MP Ultra-wide",
      keyFeatures: [
        "A17 Pro Chip for ultra-fast performance",
        "Ceramic Shield for durability",
        "Advanced photography and videography tools",
        "5G ready for lightning-fast connectivity",
      ],
      description:
        "The iPhone 15 Pro Max delivers revolutionary features in a sleek titanium design. From stunning photography to blazing performance, it redefines what a smartphone can do.",
    },

    {
      name: "Backpack Set",
      slug: "backpack-set",
      category: "Backpack",
      image: "/images/images (28).jpeg",
      price: 30,
      brand: "Joy-Smart",
      rating: 5,
      numReview: 8,
      countInStock: 10,
      color: "Black and Gray",
      dimensions: "18 x 14 x 6 inches",
      material: "Water-resistant Polyester",
      keyFeatures: [
        "Spacious compartments for organization",
        "Padded shoulder straps for comfort",
        "Durable and lightweight material",
        "Includes matching smaller pouch",
      ],
      description:
        "This backpack set is ideal for students, travelers, or professionals. It offers ample storage space and comes with a matching pouch for added utility.",
    },

    {
      name: "Nike Shoes NBA Edition",
      slug: "nike-fashion",
      category: "Canvas Shoes",
      image: "/images/images (19).jpeg",
      price: 40,
      brand: "Nike",
      rating: 5,
      numReview: 8,
      countInStock: 10,
      color: "White with Red Accents",
      size: [38, 39, 40, 41, 42, 43, 44],
      material: "Canvas upper, rubber sole",
      keyFeatures: [
        "Bold NBA-inspired design",
        "Lightweight and durable construction",
        "Breathable material for comfort",
        "Excellent grip for casual or sporty use",
      ],
      description:
        "Stand out with the Nike NBA Edition shoes. Featuring a bold design and premium materials, these shoes combine style with functionality for any occasion.",
    },

    {
      name: "Casio Sleek Watch",
      slug: "casio-watch",
      category: "Watch",
      image: "/images/images (34).jpeg",
      price: 40,
      brand: "Casio",
      rating: 5,
      numReview: 8,
      countInStock: 10,
      color: "Black",
      material: "Stainless Steel Case, Resin Band",
      waterResistance: "50 meters",
      keyFeatures: [
        "Minimalistic yet stylish design",
        "Precise quartz movement",
        "Durable and comfortable resin band",
        "Water-resistant for daily activities",
      ],
      description:
        "The Casio Sleek Watch is perfect for those who value simplicity and functionality. Its modern design fits any occasion while ensuring durability and precision.",
    },

    {
      name: "Laptop Bag",
      slug: "laptop-bag-joySmart",
      category: "Backpack",
      image: "/images/images (27).jpeg",
      price: 20,
      brand: "Joy-Smart",
      rating: 5,
      numReview: 8,
      countInStock: 10,
      color: "Dark Gray",
      dimensions: "16 x 12 x 4 inches",
      material: "Waterproof Nylon",
      keyFeatures: [
        "Protective padding for laptops up to 15.6 inches",
        "Multiple compartments for organization",
        "Water-resistant material to protect belongings",
        "Adjustable and padded shoulder straps",
      ],
      description:
        "This sleek laptop bag offers practicality and style. With ample space and protective features, it’s the perfect companion for work or travel.",
    },

    {
      name: "MacBook Air",
      slug: "apple-macbook-air",
      category: "Laptop",
      image: "/images/images (31).jpeg",
      price: 540,
      brand: "Apple",
      rating: 5,
      numReview: 8,
      countInStock: 10,
      color: "Midnight",
      screenSize: "13.6 inches",
      processor: "Apple M2 Chip",
      RAM: "8GB",
      storage: "256GB SSD",
      keyFeatures: [
        "Silent and efficient fanless design",
        "Liquid Retina display for stunning visuals",
        "Long battery life, up to 18 hours",
        "Ultrathin and lightweight for portability",
      ],
      description:
        "Redefine productivity with the MacBook Air. Designed for performance on the go, it offers powerful features in a compact and stylish package.",
    },
    {
      name: "Edifice Stylish Watch",
      slug: "stylish-fashion-men-watch",
      category: "Watch",
      image: "/images/images (35).jpeg",
      price: 40,
      brand: "Edifice",
      rating: 5,
      numReview: 8,
      countInStock: 10,
      color: "Silver with Blue Dial",
      material: "Stainless Steel",
      waterResistance: "100 meters",
      keyFeatures: [
        "Chronograph functionality for precision",
        "Stylish design with a bold blue dial",
        "High-quality stainless steel construction",
        "Water-resistant for swimming and snorkeling",
      ],
      description:
        "Elevate your style with the Edifice Stylish Watch. This elegant timepiece combines functionality with a sleek design, perfect for both formal and casual occasions.",
    },

    {
      name: "Nike Bouncer Shoes",
      slug: "brouncer-nike",
      category: "Canvas Shoes",
      image: "/images/images (33).jpeg",
      price: 40,
      brand: "Nike",
      rating: 5,
      numReview: 8,
      countInStock: 10,
      color: "Black with White Sole",
      size: [39, 40, 41, 42, 43, 44, 45],
      material: "Breathable mesh upper, rubber sole",
      keyFeatures: [
        "Enhanced cushioning for comfort",
        "Modern, athletic-inspired design",
        "Durable rubber outsole for traction",
        "Versatile for sports or casual outings",
      ],
      description:
        "Step into unmatched comfort with Nike Bouncer Shoes. Built for performance and style, these shoes are perfect for daily wear or sporty activities.",
    },

    {
      name: "HP Pavilion 15",
      slug: "hp-pavillion-15",
      category: "Laptop",
      image: "/images/images (29).jpeg",
      price: 140,
      brand: "HP",
      rating: 5,
      numReview: 8,
      countInStock: 10,
      color: "Silver",
      screenSize: "15.6 inches",
      processor: "Intel Core i5",
      RAM: "8GB",
      storage: "256GB SSD",
      operatingSystem: "Windows 11",
      keyFeatures: [
        "Full HD display with vibrant colors",
        "Powerful Intel processor for multitasking",
        "Lightweight design for portability",
        "Integrated HD webcam for video calls",
      ],
      description:
        "The HP Pavilion 15 is a versatile laptop designed for productivity and entertainment. With its robust performance and stylish design, it's ideal for both work and play.",
    },

    {
      name: "Apple Mac Retina",
      slug: "macbook-retina",
      category: "Laptop",
      image: "/images/images (30).jpeg",
      price: 560,
      brand: "Apple",
      rating: 5,
      numReview: 8,
      countInStock: 10,
      color: "Silver",
      screenSize: "13.3 inches",
      processor: "Apple M1 Chip",
      RAM: "16GB",
      storage: "1TB SSD",
      keyFeatures: [
        "Retina display with True Tone technology",
        "Blazing-fast performance with the M1 chip",
        "Backlit Magic Keyboard with Touch ID",
        "Silent and efficient operation",
      ],
      description:
        "Take your work to the next level with the Apple Mac Retina. Its powerful performance and crystal-clear Retina display make it a favorite among professionals.",
    },

    {
      name: "iPhone 13 Pro Max",
      slug: "iphone13",
      category: "Mobile",
      image: "/images/images (25).jpeg",
      price: 240,
      brand: "Apple",
      rating: 5,
      numReview: 8,
      countInStock: 0,
      color: "Graphite",
      screenSize: "6.7 inches",
      storage: ["128GB", "256GB", "512GB"],
      camera: "12MP Triple Camera System",
      keyFeatures: [
        "A15 Bionic Chip for seamless performance",
        "ProMotion technology for fluid display",
        "Night mode for incredible low-light photography",
        "Ceramic Shield for ultimate durability",
      ],
      description:
        "The iPhone 13 Pro Max redefines performance and photography. With its advanced camera system and powerful chip, it delivers an unparalleled smartphone experience.",
    },

    {
      name: "Lavida Men Shoes",
      slug: "lavida-shoes-fashion",
      category: "Canvas Shoes",
      image: "/images/images (17).jpeg",
      price: 40,
      brand: "Lavida",
      rating: 5,
      numReview: 8,
      countInStock: 10,
      color: "Brown",
      size: [39, 40, 41, 42, 43, 44],
      material: "Suede upper, rubber sole",
      keyFeatures: [
        "Classic design for versatile wear",
        "Comfortable fit with cushioned sole",
        "Durable suede material",
        "Perfect for formal and casual outings",
      ],
      description:
        "Step up your fashion game with Lavida Men Shoes. These shoes combine comfort and style, making them a great choice for any occasion.",
    },

    {
      name: "Apple Watch Series 8",
      slug: "stylish-watch",
      category: "Watch",
      image: "/images/images (21).jpeg",
      price: 110,
      brand: "Apple",
      rating: 5,
      numReview: 8,
      countInStock: 10,
      color: "Starlight Aluminum Case",
      strapMaterial: "Silicone",
      screenSize: "1.9 inches",
      waterResistance: "50 meters",
      keyFeatures: [
        "Advanced health monitoring features",
        "Always-On Retina display",
        "Fast charging capabilities",
        "Supports apps for fitness and productivity",
      ],
      description:
        "The Apple Watch Series 8 combines cutting-edge technology with stylish design. Stay connected and monitor your health with this premium smartwatch.",
    },
    {
      name: "MacBook Air",
      slug: "apple-macbook-air",
      category: "Laptop",
      image: "/images/images (31).jpeg",
      price: 540,
      brand: "Apple",
      rating: 5,
      numReview: 8,
      countInStock: 10,
      color: "Space Gray",
      screenSize: "13.3 inches",
      processor: "Apple M1 Chip",
      RAM: "8GB",
      storage: "512GB SSD",
      batteryLife: "Up to 18 hours",
      keyFeatures: [
        "Ultra-thin and lightweight design",
        "Stunning Retina display with P3 wide color",
        "M1 chip for lightning-fast performance",
        "Silent operation with no fan",
      ],
      description:
        "The MacBook Air is the ultimate portable powerhouse. Its sleek design, advanced M1 chip, and all-day battery life make it perfect for students, professionals, and creatives on the go.",
    },

    {
      name: "MacBook Pro",
      slug: "apple-macbook-pro",
      category: "Laptop",
      image: "/images/images (32).jpeg",
      price: 640,
      brand: "Apple",
      rating: 5,
      numReview: 8,
      countInStock: 10,
      color: "Silver",
      screenSize: "14 inches",
      processor: "Apple M2 Chip",
      RAM: "16GB",
      storage: "1TB SSD",
      batteryLife: "Up to 20 hours",
      keyFeatures: [
        "XDR Liquid Retina display for breathtaking visuals",
        "M2 chip for industry-leading performance",
        "ProMotion technology for smooth scrolling",
        "MagSafe charging and advanced cooling system",
      ],
      description:
        "Designed for professionals, the MacBook Pro delivers unrivaled performance and features. Whether editing videos or running intensive apps, it handles everything effortlessly.",
    },

    {
      name: "Laptop Bag",
      slug: "laptop-bag-joySmart",
      category: "Backpack",
      image: "/images/images (27).jpeg",
      price: 20,
      brand: "JoySmart",
      rating: 5,
      numReview: 8,
      countInStock: 10,
      color: "Black",
      material: "Nylon with padded compartments",
      capacity: "Fits laptops up to 15.6 inches",
      keyFeatures: [
        "Water-resistant material for extra protection",
        "Multiple compartments for organization",
        "Padded straps for comfort",
        "Durable and lightweight design",
      ],
      description:
        "The JoySmart Laptop Bag is the perfect travel companion for professionals. It offers superior protection for your devices and ample storage for all your essentials.",
    },

    {
      name: "Backpack Set",
      slug: "backpack-set",
      category: "Backpack",
      image: "/images/images (28).jpeg",
      price: 30,
      brand: "JoySmart",
      rating: 5,
      numReview: 8,
      countInStock: 10,
      color: "Blue and Gray",
      material: "Polyester",
      capacity: "Large capacity for books, laptops, and accessories",
      keyFeatures: [
        "Comes with a matching smaller pouch",
        "Adjustable straps for a custom fit",
        "Stylish and practical design",
        "Ideal for school, work, or travel",
      ],
      description:
        "Upgrade your style with the JoySmart Backpack Set. Its durable construction and modern design make it perfect for everyday use, whether you're heading to class or exploring new destinations.",
    },

    {
      name: "Casio Sleek Watch",
      slug: "casio-watch",
      category: "Watch",
      image: "/images/images (34).jpeg",
      price: 40,
      brand: "Casio",
      rating: 5,
      numReview: 8,
      countInStock: 10,
      color: "Black with Silver Accents",
      material: "Stainless Steel and Resin",
      waterResistance: "50 meters",
      keyFeatures: [
        "Slim design for a modern look",
        "Quartz movement for accurate timekeeping",
        "Scratch-resistant mineral glass",
        "Suitable for daily use and casual outings",
      ],
      description:
        "The Casio Sleek Watch is a blend of simplicity and style. Perfect for any occasion, its lightweight design and reliable features make it an excellent choice for everyday wear.",
    },

    {
      name: "iPhone 15 Pro Max",
      slug: "iphone15",
      category: "Mobile",
      image: "/images/images (26).jpeg",
      price: 440,
      brand: "Apple",
      rating: 5,
      numReview: 8,
      countInStock: 10,
      color: "Deep Purple",
      screenSize: "6.7 inches",
      storage: ["256GB", "512GB", "1TB"],
      camera: "48MP Pro Camera System",
      keyFeatures: [
        "A17 Bionic Chip for extraordinary speed",
        "Dynamic Island and Always-On display",
        "Cinematic mode for professional video recording",
        "Crash detection and advanced safety features",
      ],
      description:
        "The iPhone 15 Pro Max is Apple's latest innovation. With groundbreaking performance, an exceptional camera system, and a sleek design, it's the perfect choice for tech enthusiasts.",
    },

    {
      name: "Apple Watch Ultra",
      slug: "apple-fashion-watch",
      category: "Watch",
      image: "/images/images (20).jpeg",
      price: 90,
      brand: "Apple",
      rating: 5,
      numReview: 8,
      countInStock: 10,
      color: "Titanium Case with Ocean Band",
      screenSize: "2 inches",
      waterResistance: "100 meters",
      keyFeatures: [
        "Extremely durable with aerospace-grade titanium",
        "Precise GPS for outdoor adventures",
        "Advanced health and fitness tracking",
        "Customizable action button",
      ],
      description:
        "Designed for the adventurous, the Apple Watch Ultra combines rugged durability with cutting-edge features. It's the ultimate smartwatch for extreme environments and outdoor enthusiasts.",
    },
    {
      name: "Edifice Stylish Watch",
      slug: "stylish-fashion-men-watch",
      category: "Watch",
      image: "/images/images (35).jpeg",
      price: 40,
      brand: "Edifice",
      rating: 5,
      numReview: 8,
      countInStock: 10,
      color: "Silver and Black",
      material: "Stainless Steel",
      waterResistance: "100 meters",
      keyFeatures: [
        "Bold and elegant design",
        "Chronograph functionality",
        "Scratch-resistant mineral glass",
        "Perfect for business and formal settings",
      ],
      description:
        "The Edifice Stylish Watch combines sophistication with functionality. Its sleek design and precision engineering make it a timeless accessory for modern professionals.",
    },

    {
      name: "Nike Men's Shoes",
      slug: "brouncer-nike",
      category: "Canvas Shoes",
      image: "/images/images (33).jpeg",
      price: 40,
      brand: "Nike",
      rating: 5,
      numReview: 8,
      countInStock: 10,
      color: "Black and White",
      material: "Synthetic Mesh with Rubber Sole",
      keyFeatures: [
        "Breathable and lightweight design",
        "Durable outsole for enhanced grip",
        "Ideal for casual wear and training",
        "Signature Nike branding",
      ],
      description:
        "Elevate your style with the Nike Men's Shoes. Designed for comfort and durability, these sneakers are perfect for everyday wear or hitting the gym.",
    },

    {
      name: "HP Pavilion 15",
      slug: "hp-pavillion-15",
      category: "Laptop",
      image: "/images/images (29).jpeg",
      price: 140,
      brand: "HP",
      rating: 5,
      numReview: 8,
      countInStock: 10,
      color: "Silver",
      screenSize: "15.6 inches",
      processor: "Intel Core i5 11th Gen",
      RAM: "8GB",
      storage: "256GB SSD",
      batteryLife: "Up to 10 hours",
      keyFeatures: [
        "Micro-edge display for immersive visuals",
        "Lightweight and portable design",
        "Fast charging support",
        "Powerful performance for work and entertainment",
      ],
      description:
        "The HP Pavilion 15 is a versatile laptop with sleek aesthetics and powerful internals. Ideal for students, professionals, and multitaskers alike.",
    },

    {
      name: "Apple Mac Retina",
      slug: "macbook-retina",
      category: "Laptop",
      image: "/images/images (30).jpeg",
      price: 560,
      brand: "Apple",
      rating: 5,
      numReview: 8,
      countInStock: 10,
      color: "Silver",
      screenSize: "16 inches",
      processor: "M1 Pro Chip",
      RAM: "16GB",
      storage: "1TB SSD",
      batteryLife: "Up to 21 hours",
      keyFeatures: [
        "High-resolution Retina display",
        "Unparalleled M1 Pro chip performance",
        "Studio-quality microphones and speakers",
        "Thunderbolt ports for fast connectivity",
      ],
      description:
        "The Apple Mac Retina is a powerhouse designed for creatives and professionals. Its stunning display and top-tier performance redefine the laptop experience.",
    },

    {
      name: "Backpack Set",
      slug: "backpack-set",
      category: "Backpack",
      image: "/images/images (28).jpeg",
      price: 30,
      brand: "JoySmart",
      rating: 5,
      numReview: 8,
      countInStock: 10,
      color: "Gray with Orange Accents",
      material: "Waterproof Polyester",
      capacity: "Large enough for 17-inch laptops",
      keyFeatures: [
        "Adjustable straps for extra comfort",
        "Dual compartments for better organization",
        "Lightweight and travel-friendly",
        "Durable and tear-resistant material",
      ],
      description:
        "The JoySmart Backpack Set offers functionality and style. Its ergonomic design and spacious compartments make it perfect for school, work, or weekend getaways.",
    },
  ],
};
export default data;
